proxy:
  secretToken: "b95e49fd7e5b19e12253e36266d92e0b3adcde2b519b7ac56674d58116e45287"

prePuller:
  hook:
    enabled: false

auth:
  type: dummy
  dummy:
    password: 'CADRE'
  admin:
    users:
      - IUNItester
  whitelist:
    users:
      - IUNItester
      - 2ndTester

cull:
  enabled: false
          
singleuser:
  # Get the latest image tag at:
  # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
  # https://hub.docker.com/u/tensorflow/
  # https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/
  # Inspect the Dockerfile at:
  # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
  image:
  name: jupyter/minimal-notebook
  tag: 7f1482f5a136
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:7f1482f5a136
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:7f1482f5a136
    - display_name: "Tensorflow environment"
      description: "The Jupyter Stacks TF image with CPU"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:7f1482f5a136
    - display_name: "Dedicated, 5 CPUs & 48GB RAM, 1 NVIDIA Tesla K80 GPU"
      description: "By selecting this choice, you will be assigned a environment that will run on a dedicated machine with a single GPU, just for you."
      kubespawner_override:
        image: gcr.io/kubeflow-images-public/tensorflow-1.12.0-notebook-gpu:v-base-52cbb4c-1258
        cpu:
          limit: 5
          guarantee: 1
        memory:
          limit: 48G
          guarantee: 8G
        extra_resource_limits:
          nvidia.com/gpu: "1"
        storage:
          capacity: 30Gi
